general {
    lock_cmd = pidof hyprlock || hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

# Sleep after 10 minutes of inactivity
listener {
    timeout = 600
    on-timeout = systemctl suspend
}

# Shut down after 1 hour of inactivity
listener {
    timeout = 3600
    on-timeout = systemctl poweroff
}
