# --- Main Colors ---
background            #0e1513
foreground            #dee4e0
cursor                #dee4e0
cursor_text_color     #0e1513

selection_background  #334b45
selection_foreground  #cde8e0

url_color             #aacbe4

# --- ANSI Colors ---
color0                #0e1513
color1                #ffb4ab
color2                #aacbe4
color3                #b1ccc4
color4                #84d6c2
color5                #aacbe4
color6                #b1ccc4
color7                #dee4e0

color8                #3f4946
color9                #93000a
color10               #2a4a5f
color11               #334b45
color12               #005144
color13               #334b45
color14               #2a4a5f
color15               #bfc9c4

# --- Starship Prompt Bubbles ---
color255              #005144
color254              #84d6c2
color253              #334b45
color252              #b1ccc4
color251              #2a4a5f
color250              #aacbe4
color249              #93000a
color248              #ffb4ab

color232              #a0f2de
color233              #00382e
color234              #cde8e0
color235              #1d352f
color236              #c8e6ff
color237              #113348
color238              #ffdad6
color239              #690005
color240              #a0f2de

# Matched with unthemed light/dark
color243              #84d6c2
color244              #ffb4ab
color245              #3f4946

# --- UI Elements ---
active_tab_foreground   #00382e
active_tab_background   #84d6c2
inactive_tab_foreground #a0f2de
inactive_tab_background #005144

active_border_color     #84d6c2
inactive_border_color   #89938f

# --- Marks ---
mark1_foreground        #00201a
mark1_background        #a0f2de
mark2_foreground        #06201a
mark2_background        #cde8e0
mark3_foreground        #001e2e
mark3_background        #c8e6ff
