include= ~/.config/foot/foot-colors.ini

[main]
font=Maple Mono NF CN:weight=semibold:size=12
shell=zsh
initial-window-size-pixels=640x400
pad=23x20

[tweak]
sixel=yes

# Includes theme file (matches Kitty's theme include)
[cursor]
style=beam

[colors-dark]
alpha=0.80
blur=yes


